name: WorldEdit
main: com.sk89q.worldedit.bukkit.WorldEditPlugin
version: "${project.version}"
commands:
    chunkinfo:
        description: Get information about the chunk that you are inside
        usage: /<command> 
    listchunks:
        description: List chunks that your selection includes
        usage: /<command> 
    delchunks:
        description: Delete chunks that your selection includes
        usage: /<command> 
    clearclipboard:
        description: Clear your clipboard
        usage: /<command> 
    /load:
        description: Load a schematic into your clipboard
        usage: /<command> <filename>
    /save:
        description: Save a schematic into your clipboard
        usage: /<command> <filename>
    /copy:
        description: Copy the selection to the clipboard
        usage: /<command> 
    /flip:
        description: Flip the contents of the clipboard
        usage: /<command> [dir]
    /rotate:
        description: Rotate the contents of the clipboard
        usage: /<command> <angle-in-degrees>
    /cut:
        description: Cut the selection to the clipboard
        usage: /<command> [leave-id]
    /paste:
        description: Paste the clipboard's contents
        usage: /<command> [-ao] 
    we:
        description: WorldEdit commands
        usage: /<command> 
        aliases: ['worldedit']
    toggleplace:
        description: 
        usage: /<command> 
    searchitem:
        description: Search for an item
        usage: /<command> [-bi] <query>
        aliases: ['/l', 'search']
    /limit:
        description: Modify block change limit
        usage: /<command> <limit>
    /hcyl:
        description: Generate a hollow cylinder
        usage: /<command> <block> <radius> [height] 
    /cyl:
        description: Generate a cylinder
        usage: /<command> <block> <radius> [height] 
    /hsphere:
        description: Generate a hollow sphere
        usage: /<command> <block> <radius> [raised?] 
    /sphere:
        description: Generate a filled sphere
        usage: /<command> <block> <radius> [raised?] 
    forestgen:
        description: Generate a forest
        usage: /<command> [size] [type] [density]
    pumpkins:
        description: Generate pumpkin patches
        usage: /<command> [size]
    clearhistory:
        description: Clear your history
        usage: /<command> 
    /redo:
        description: Redoes the last action (from history)
        usage: /<command> [times]
        aliases: ['redo']
    /undo:
        description: Undoes the last action
        usage: /<command> [times]
        aliases: ['undo']
    unstuck:
        description: Escape from being stuck inside a block
        usage: /<command> 
    ascend:
        description: Go up a floor
        usage: /<command> 
    descend:
        description: Go down a floor
        usage: /<command> 
    thru:
        description: Passthrough walls
        usage: /<command> 
    jumpto:
        description: Teleport to a location
        usage: /<command> 
    ceil:
        description: Go to the celing
        usage: /<command> [clearance]
    up:
        description: Go upwards some distance
        usage: /<command> <block>
    /overlay:
        description: Set a block on top of blocks in the region
        usage: /<command> <block>
    /walls:
        description: Build the four sides of the selection
        usage: /<command> <block>
    /faces:
        description: Build the walls, ceiling, and roof of a selection
        usage: /<command> <block>
        aliases: ['/outline']
    /smooth:
        description: Smooth the elevation in the selection
        usage: /<command> [iterations]
    /regen:
        description: Regenerates the contents of the selection
        usage: /<command> 
    /replace:
        description: Replace all blocks in the selection with another
        usage: /<command> [from-block] <to-block>
    /stack:
        description: Repeat the contents of the selection
        usage: /<command> [-a] [count] [direction]
    /set:
        description: Set all the blocks inside the selection to a block
        usage: /<command> <block>
    /move:
        description: Move the contents of the selection
        usage: /<command> [count] [direction] [leave-id]
    .s:
        description: Execute last CraftScript
        usage: /<command> [args...]
    cs:
        description: Execute a CraftScript
        usage: /<command> <filename> [args...]
    /chunk:
        description: Set the selection to your current chunk
        usage: /<command> 
    /pos1:
        description: Set position 1
        usage: /<command> 
    /pos2:
        description: Set position 2
        usage: /<command> 
    /hpos1:
        description: Set position 1 to targeted block
        usage: /<command> 
    /hpos2:
        description: Set position 2 to targeted block
        usage: /<command> 
    /wand:
        description: Get the wand object
        usage: /<command> 
    toggleeditwand:
        description: Toggle functionality of the edit wand
        usage: /<command> 
    /contract:
        description: Contract the selection area
        usage: /<command> <amount> [reverse-amount] [direction]
    /outset:
        description: Outset the selection area
        usage: /<command> [-hv] <amount>
    /distr:
        description: Get the distribution of blocks in the selection
        usage: /<command> [-c] 
    /count:
        description: Counts the number of a certain type of block
        usage: /<command> <block>
    /size:
        description: Get information about the selection
        usage: /<command> 
    /shift:
        description: Shift the selection area
        usage: /<command> <amount> [direction]
    /expand:
        description: Expand the selection area
        usage: /<command> <amount> [reverse-amount] <direction>
    /sel:
        description: Choose a region selector
        usage: /<command> [type]
        aliases: [',']
    /inset:
        description: Inset the selection area
        usage: /<command> [-hv] <amount>
    snapshot:
        description: Snapshot commands
        usage: /<command> 
        aliases: ['snap']
    restore:
        description: Restore the selection from a snapshot
        usage: /<command> [snapshot]
        aliases: ['/restore']
    /:
        description: Toggle the super pickaxe pickaxe function
        usage: /<command> 
        aliases: [',']
    superpickaxe:
        description: Select super pickaxe mode
        usage: /<command> 
        aliases: ['pickaxe', 'sp']
    tool:
        description: Select a tool to bind
        usage: /<command> 
    mat:
        description: Set the brush material
        usage: /<command> [pattern]
        aliases: ['material', 'fill']
    size:
        description: Set the brush size
        usage: /<command> [pattern]
    mask:
        description: Set the brush mask
        usage: /<command> [mask]
    none:
        description: Turn off all superpickaxe alternate modes
        usage: /<command> 
    repl:
        description: Block replacer tool
        usage: /<command> <block>
    cycler:
        description: Block data cycler tool
        usage: /<command> 
    brush:
        description: Brush tool
        usage: /<command> 
        aliases: ['br']
    info:
        description: Block information tool
        usage: /<command> 
    tree:
        description: Tree generator tool
        usage: /<command> [type]
    deltree:
        description: Floating tree remover tool
        usage: /<command>
    /fillr:
        description: Fill a hole recursively
        usage: /<command>  <block> <radius> [depth] 
    fixlava:
        description: Fix lava to be stationary
        usage: /<command> <radius>
    fixwater:
        description: Fix water to be stationary
        usage: /<command> <radius>
    removeabove:
        description: Remove blocks above your head. 
        usage: /<command> [size] [height] 
    removebelow:
        description: Remove blocks below your head. 
        usage: /<command> [size] [height] 
    removenear:
        description: Remove blocks near you.
        usage: /<command> <block> [size] 
    replacenear:
        description: Replace nearby blocks
        usage: /<command> <size> <from-id> <to-id> 
    snow:
        description: Simulates snow
        usage: /<command> [radius]
    thaw:
        description: Thaws the area
        usage: /<command> [radius]
    ex:
        description: Extinguish nearby fire
        usage: /<command> [radius]
        aliases: ['ext', 'extinguish']
    butcher:
        description: Kill all or nearby mobs
        usage: /<command> [radius]
    remove:
        description: Remove all entities of a type
        usage: /<command> <type> <radius>
        aliases: ['rem', 'rement']
    /fill:
        description: Fill a hole
        usage: /<command>  <block> <radius> [depth] 
    /drain:
        description: Drain a pool
        usage: /<command> <radius>
