name: WorldEdit
main: com.sk89q.worldedit.bukkit.WorldEditPlugin
version: ${project.version}
commands:
    chunkinfo:
        description: Get information about the chunk that you are inside
        usage: /<command>
    listchunks:
        description: List chunks that your selection includes
        usage: /<command>
    delchunks:
        description: Delete chunks that your selection includes
        usage: /<command>
    /load:
        description: Load a schematic into your clipboard
        usage: /<command> <filename>
    /save:
        description: Save a schematic into your clipboard
        usage: /<command> <filename>
    /copy:
        description: Copy the selection to the clipboard
        usage: /<command>
    /flip:
        description: Flip the contents of the clipboard.
        usage: /<command> [-p] [dir]
    /rotate:
        description: Rotate the contents of the clipboard
        usage: /<command> <angle-in-degrees>
    /cut:
        description: Cut the selection to the clipboard
        usage: /<command> [leave-id]
    /paste:
        description: Paste the clipboard's contents
        usage: /<command> [-ao]
    clearclipboard:
        description: Clear your clipboard
        usage: /<command>
    /limit:
        description: Modify block change limit
        usage: /<command> <limit>
    /gmask:
        description: Set the global mask
        usage: /<command> [mask]
        aliases: ['gmask']
    we:
        description: WorldEdit commands
        usage: /<command>
        aliases: ['worldedit']
    /fast:
        description: Toggle fast mode
        usage: /<command>
    /toggleplace:
        description: Switch between your position and pos1 for placement
        usage: /<command>
        aliases: ['toggleplace']
    /searchitem:
        description: Search for an item
        usage: /<command> [-bi] <query>
        aliases: ['/l', '/search', 'searchitem', 'search']
    /hcyl:
        description: Generate a hollow cylinder
        usage: /<command> <block> <radius> [height]
    /cyl:
        description: Generate a cylinder
        usage: /<command> <block> <radius> [height]
    /hsphere:
        description: Generate a hollow sphere.
        usage: /<command> [-q] <block> <radius>[,<radius>,<radius>] [raised?]
    /sphere:
        description: Generate a filled sphere.
        usage: /<command> [-q] <block> <radius>[,<radius>,<radius>] [raised?]
    forestgen:
        description: Generate a forest
        usage: /<command> [size] [type] [density]
    pumpkins:
        description: Generate pumpkin patches
        usage: /<command> [size]
    /pyramid:
        description: Generate a filled pyramid
        usage: /<command> <block> <range>
    /hpyramid:
        description: Generate a hollow pyramid
        usage: /<command> <block> <range>
    /undo:
        description: Undoes the last action
        usage: /<command> [times] [player]
        aliases: ['undo']
    /redo:
        description: Redoes the last action (from history)
        usage: /<command> [times] [player]
        aliases: ['redo']
    /clearhistory:
        description: Clear your history
        usage: /<command>
        aliases: ['clearhistory']
    unstuck:
        description: Escape from being stuck inside a block
        usage: /<command>
        aliases: ['!']
    ascend:
        description: Go up a floor
        usage: /<command> [# of levels]
    descend:
        description: Go down a floor
        usage: /<command> [# of floors]
    ceil:
        description: Go to the celing
        usage: /<command> [clearance]
    thru:
        description: Passthrough walls
        usage: /<command>
    jumpto:
        description: Teleport to a location
        usage: /<command>
    up:
        description: Go upwards some distance
        usage: /<command> <block>
    /replace:
        description: Replace all blocks in the selection with another
        usage: /<command> [-f] [from-block] <to-block>
    /stack:
        description: Repeat the contents of the selection
        usage: /<command> [-sa] [count] [direction]
    /set:
        description: Set all the blocks inside the selection to a block
        usage: /<command> <block>
    /overlay:
        description: Set a block on top of blocks in the region
        usage: /<command> <block>
    /naturalize:
        description: 3 layers of dirt on top then rock below
        usage: /<command>
    /walls:
        description: Build the four sides of the selection
        usage: /<command> <block>
    /faces:
        description: Build the walls, ceiling, and floor of a selection
        usage: /<command> <block>
        aliases: ['/outline']
    /smooth:
        description: Smooth the elevation in the selection
        usage: /<command> [-n] [iterations]
    /move:
        description: Move the contents of the selection
        usage: /<command> [-s] [count] [direction] [leave-id]
    /regen:
        description: Regenerates the contents of the selection
        usage: /<command>
    cs:
        description: Execute a CraftScript
        usage: /<command> <filename> [args...]
    .s:
        description: Execute last CraftScript
        usage: /<command> [args...]
    /count:
        description: Counts the number of a certain type of block
        usage: /<command> <block>
    /size:
        description: Get information about the selection
        usage: /<command>
    /shift:
        description: Shift the selection area
        usage: /<command> <amount> [direction]
    /chunk:
        description: Set the selection to your current chunk.
        usage: /<command> [-s]
    /expand:
        description: Expand the selection area
        usage: /<command> <amount> [reverse-amount] <direction>
    /contract:
        description: Contract the selection area
        usage: /<command> <amount> [reverse-amount] [direction]
    /pos1:
        description: Set position 1
        usage: /<command> [coordinates]
    /pos2:
        description: Set position 2
        usage: /<command> [coordinates]
    /hpos1:
        description: Set position 1 to targeted block
        usage: /<command>
    /hpos2:
        description: Set position 2 to targeted block
        usage: /<command>
    /wand:
        description: Get the wand object
        usage: /<command>
    toggleeditwand:
        description: Toggle functionality of the edit wand
        usage: /<command>
    /outset:
        description: Outset the selection area
        usage: /<command> [-hv] <amount>
    /inset:
        description: Inset the selection area
        usage: /<command> [-hv] <amount>
    /distr:
        description: Get the distribution of blocks in the selection
        usage: /<command> [-c]
    /sel:
        description: Choose a region selector
        usage: /<command> [type]
        aliases: [';']
    snapshot:
        description: Snapshot commands
        usage: /<command>
        aliases: ['snap']
    restore:
        description: Restore the selection from a snapshot
        usage: /<command> [snapshot]
        aliases: ['/restore']
    size:
        description: Set the brush size
        usage: /<command> [pattern]
    mask:
        description: Set the brush mask
        usage: /<command> [mask]
    /:
        description: Toggle the super pickaxe pickaxe function
        usage: /<command> [on|off]
        aliases: [',']
    superpickaxe:
        description: Select super pickaxe mode
        usage: /<command>
        aliases: ['pickaxe', 'sp']
    tool:
        description: Select a tool to bind
        usage: /<command>
    mat:
        description: Set the brush material
        usage: /<command> [pattern]
        aliases: ['material', 'fill']
    range:
        description: Set the brush range
        usage: /<command> [pattern]
    info:
        description: Block information tool
        usage: /<command>
    none:
        description: Unbind all bound tools
        usage: /<command>
    tree:
        description: Tree generator tool
        usage: /<command> [type]
    repl:
        description: Block replacer tool
        usage: /<command> <block>
    cycler:
        description: Block data cycler tool
        usage: /<command>
    floodfill:
        description: Flood fill tool
        usage: /<command> <pattern> <range>
        aliases: ['flood']
    brush:
        description: Brush tool
        usage: /<command>
        aliases: ['br']
    deltree:
        description: Floating tree remover tool
        usage: /<command>
    farwand:
        description: Wand at a distance tool
        usage: /<command>
    lrbuild:
        description: Long-range building tool
        usage: /<command> <leftclick block> <rightclick block>
        aliases: ['/lrbuild']
    remove:
        description: Remove all entities of a type
        usage: /<command> <type> <radius>
        aliases: ['rem', 'rement']
    /fill:
        description: Fill a hole
        usage: /<command> <block> <radius> [depth]
    /fillr:
        description: Fill a hole recursively
        usage: /<command> <block> <radius> [depth]
    /drain:
        description: Drain a pool
        usage: /<command> <radius>
    /fixlava:
        description: Fix lava to be stationary
        usage: /<command> <radius>
        aliases: ['fixlava']
    /fixwater:
        description: Fix water to be stationary
        usage: /<command> <radius>
        aliases: ['fixwater']
    /removeabove:
        description: Remove blocks above your head.
        usage: /<command> [size] [height]
        aliases: ['removeabove']
    /removebelow:
        description: Remove blocks below you.
        usage: /<command> [size] [height]
        aliases: ['removebelow']
    /removenear:
        description: Remove blocks near you.
        usage: /<command> <block> [size]
        aliases: ['removenear']
    /replacenear:
        description: Replace nearby blocks
        usage: /<command> [-f] <size> <from-id> <to-id>
        aliases: ['replacenear']
    /snow:
        description: Simulates snow
        usage: /<command> [radius]
        aliases: ['snow']
    /thaw:
        description: Thaws the area
        usage: /<command> [radius]
        aliases: ['thaw']
    /green:
        description: Greens the area
        usage: /<command> [radius]
        aliases: ['green']
    /ex:
        description: Extinguish nearby fire
        usage: /<command> [radius]
        aliases: ['/ext', '/extinguish', 'ex', 'ext', 'extinguish']
    butcher:
        description: Kill all or nearby mobs
        usage: /<command> [-p] [radius]


# Permissions aren't here. Read http://wiki.sk89q.com/wiki/WEPIF/DinnerPerms
# for how WorldEdit permissions actually work.
