name: WorldEdit
main: com.sk89q.worldedit.bukkit.WorldEditPlugin
version: ${project.version}
softdepend: [Spout] #hack to fix trove errors

# Permissions aren't here. Read http://wiki.sk89q.com/wiki/WEPIF/DinnerPerms
# for how WorldEdit permissions actually work.
