name: WorldEdit
main: com.sk89q.worldedit.bukkit.WorldEditPlugin
version: "${internalVersion}-Folia"
load: STARTUP
api-version: 1.20
softdepend: [Vault]
author: EngineHub
website: https://enginehub.org/worldedit
folia-supported: true